# Generated by Django 4.2.10 on 2024-03-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_group_options_alter_studentgroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_group_size',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='min_group_size',
            field=models.SmallIntegerField(default=1),
        ),
    ]
