# Generated by Django 4.2.10 on 2024-03-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_max_group_size_product_min_group_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('id',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
